name: PR Auto Comment

permissions:
  issues: write
  pull-requests: write  # Add this line to fix the permission issue
  
on:
  pull_request:
    types: [opened]  # Trigger only when a PR is opened

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 Thanks for opening this PR, @${{ github.actor }}! Soham will review it soon. 🎯"
            })
